// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ibmwatsonapi.proxies;

/**
 * 
 */
public class RelationshipExtractionParams
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject relationshipExtractionParamsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IbmWatsonApi.RelationshipExtractionParams";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		sid("sid"),
		rt("rt"),
		txt("txt");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RelationshipExtractionParams(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IbmWatsonApi.RelationshipExtractionParams"));
	}

	protected RelationshipExtractionParams(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject relationshipExtractionParamsMendixObject)
	{
		if (relationshipExtractionParamsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IbmWatsonApi.RelationshipExtractionParams", relationshipExtractionParamsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IbmWatsonApi.RelationshipExtractionParams");

		this.relationshipExtractionParamsMendixObject = relationshipExtractionParamsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RelationshipExtractionParams.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static ibmwatsonapi.proxies.RelationshipExtractionParams initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ibmwatsonapi.proxies.RelationshipExtractionParams.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static ibmwatsonapi.proxies.RelationshipExtractionParams initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ibmwatsonapi.proxies.RelationshipExtractionParams(context, mendixObject);
	}

	public static ibmwatsonapi.proxies.RelationshipExtractionParams load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ibmwatsonapi.proxies.RelationshipExtractionParams.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of sid
	 */
	public final String getsid()
	{
		return getsid(getContext());
	}

	/**
	 * @param context
	 * @return value of sid
	 */
	public final String getsid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.sid.toString());
	}

	/**
	 * Set value of sid
	 * @param sid
	 */
	public final void setsid(String sid)
	{
		setsid(getContext(), sid);
	}

	/**
	 * Set value of sid
	 * @param context
	 * @param sid
	 */
	public final void setsid(com.mendix.systemwideinterfaces.core.IContext context, String sid)
	{
		getMendixObject().setValue(context, MemberNames.sid.toString(), sid);
	}

	/**
	 * @return value of rt
	 */
	public final String getrt()
	{
		return getrt(getContext());
	}

	/**
	 * @param context
	 * @return value of rt
	 */
	public final String getrt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.rt.toString());
	}

	/**
	 * Set value of rt
	 * @param rt
	 */
	public final void setrt(String rt)
	{
		setrt(getContext(), rt);
	}

	/**
	 * Set value of rt
	 * @param context
	 * @param rt
	 */
	public final void setrt(com.mendix.systemwideinterfaces.core.IContext context, String rt)
	{
		getMendixObject().setValue(context, MemberNames.rt.toString(), rt);
	}

	/**
	 * @return value of txt
	 */
	public final String gettxt()
	{
		return gettxt(getContext());
	}

	/**
	 * @param context
	 * @return value of txt
	 */
	public final String gettxt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.txt.toString());
	}

	/**
	 * Set value of txt
	 * @param txt
	 */
	public final void settxt(String txt)
	{
		settxt(getContext(), txt);
	}

	/**
	 * Set value of txt
	 * @param context
	 * @param txt
	 */
	public final void settxt(com.mendix.systemwideinterfaces.core.IContext context, String txt)
	{
		getMendixObject().setValue(context, MemberNames.txt.toString(), txt);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return relationshipExtractionParamsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ibmwatsonapi.proxies.RelationshipExtractionParams that = (ibmwatsonapi.proxies.RelationshipExtractionParams) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IbmWatsonApi.RelationshipExtractionParams";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
