// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ibmwatsonapi.proxies;

/**
 * 
 */
public class RelationshipExtractionRoot
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject relationshipExtractionRootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IbmWatsonApi.RelationshipExtractionRoot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		doc("IbmWatsonApi.doc");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RelationshipExtractionRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IbmWatsonApi.RelationshipExtractionRoot"));
	}

	protected RelationshipExtractionRoot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject relationshipExtractionRootMendixObject)
	{
		if (relationshipExtractionRootMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IbmWatsonApi.RelationshipExtractionRoot", relationshipExtractionRootMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IbmWatsonApi.RelationshipExtractionRoot");

		this.relationshipExtractionRootMendixObject = relationshipExtractionRootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RelationshipExtractionRoot.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static ibmwatsonapi.proxies.RelationshipExtractionRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ibmwatsonapi.proxies.RelationshipExtractionRoot.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static ibmwatsonapi.proxies.RelationshipExtractionRoot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ibmwatsonapi.proxies.RelationshipExtractionRoot(context, mendixObject);
	}

	public static ibmwatsonapi.proxies.RelationshipExtractionRoot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ibmwatsonapi.proxies.RelationshipExtractionRoot.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of doc
	 */
	public final ibmwatsonapi.proxies.RelationshipExtractionDoc getdoc() throws com.mendix.core.CoreException
	{
		return getdoc(getContext());
	}

	/**
	 * @param context
	 * @return value of doc
	 */
	public final ibmwatsonapi.proxies.RelationshipExtractionDoc getdoc(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ibmwatsonapi.proxies.RelationshipExtractionDoc result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.doc.toString());
		if (identifier != null)
			result = ibmwatsonapi.proxies.RelationshipExtractionDoc.load(context, identifier);
		return result;
	}

	/**
	 * Set value of doc
	 * @param doc
	 */
	public final void setdoc(ibmwatsonapi.proxies.RelationshipExtractionDoc doc)
	{
		setdoc(getContext(), doc);
	}

	/**
	 * Set value of doc
	 * @param context
	 * @param doc
	 */
	public final void setdoc(com.mendix.systemwideinterfaces.core.IContext context, ibmwatsonapi.proxies.RelationshipExtractionDoc doc)
	{
		if (doc == null)
			getMendixObject().setValue(context, MemberNames.doc.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.doc.toString(), doc.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return relationshipExtractionRootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ibmwatsonapi.proxies.RelationshipExtractionRoot that = (ibmwatsonapi.proxies.RelationshipExtractionRoot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IbmWatsonApi.RelationshipExtractionRoot";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
