// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ibmwatsonapi.proxies;

/**
 * 
 */
public class RelationshipExtractionMention
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject relationshipExtractionMentionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IbmWatsonApi.RelationshipExtractionMention";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text("Text"),
		Role("Role"),
		Score("Score"),
		mention("IbmWatsonApi.mention");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RelationshipExtractionMention(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IbmWatsonApi.RelationshipExtractionMention"));
	}

	protected RelationshipExtractionMention(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject relationshipExtractionMentionMendixObject)
	{
		if (relationshipExtractionMentionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IbmWatsonApi.RelationshipExtractionMention", relationshipExtractionMentionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IbmWatsonApi.RelationshipExtractionMention");

		this.relationshipExtractionMentionMendixObject = relationshipExtractionMentionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RelationshipExtractionMention.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static ibmwatsonapi.proxies.RelationshipExtractionMention initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ibmwatsonapi.proxies.RelationshipExtractionMention.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static ibmwatsonapi.proxies.RelationshipExtractionMention initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ibmwatsonapi.proxies.RelationshipExtractionMention(context, mendixObject);
	}

	public static ibmwatsonapi.proxies.RelationshipExtractionMention load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ibmwatsonapi.proxies.RelationshipExtractionMention.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Text
	 */
	public final String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of Role
	 */
	public final String getRole()
	{
		return getRole(getContext());
	}

	/**
	 * @param context
	 * @return value of Role
	 */
	public final String getRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Role.toString());
	}

	/**
	 * Set value of Role
	 * @param role
	 */
	public final void setRole(String role)
	{
		setRole(getContext(), role);
	}

	/**
	 * Set value of Role
	 * @param context
	 * @param role
	 */
	public final void setRole(com.mendix.systemwideinterfaces.core.IContext context, String role)
	{
		getMendixObject().setValue(context, MemberNames.Role.toString(), role);
	}

	/**
	 * @return value of Score
	 */
	public final java.math.BigDecimal getScore()
	{
		return getScore(getContext());
	}

	/**
	 * @param context
	 * @return value of Score
	 */
	public final java.math.BigDecimal getScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Score.toString());
	}

	/**
	 * Set value of Score
	 * @param score
	 */
	public final void setScore(java.math.BigDecimal score)
	{
		setScore(getContext(), score);
	}

	/**
	 * Set value of Score
	 * @param context
	 * @param score
	 */
	public final void setScore(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal score)
	{
		getMendixObject().setValue(context, MemberNames.Score.toString(), score);
	}

	/**
	 * @return value of mention
	 */
	public final ibmwatsonapi.proxies.RelationshipExtractionMentions getmention() throws com.mendix.core.CoreException
	{
		return getmention(getContext());
	}

	/**
	 * @param context
	 * @return value of mention
	 */
	public final ibmwatsonapi.proxies.RelationshipExtractionMentions getmention(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ibmwatsonapi.proxies.RelationshipExtractionMentions result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.mention.toString());
		if (identifier != null)
			result = ibmwatsonapi.proxies.RelationshipExtractionMentions.load(context, identifier);
		return result;
	}

	/**
	 * Set value of mention
	 * @param mention
	 */
	public final void setmention(ibmwatsonapi.proxies.RelationshipExtractionMentions mention)
	{
		setmention(getContext(), mention);
	}

	/**
	 * Set value of mention
	 * @param context
	 * @param mention
	 */
	public final void setmention(com.mendix.systemwideinterfaces.core.IContext context, ibmwatsonapi.proxies.RelationshipExtractionMentions mention)
	{
		if (mention == null)
			getMendixObject().setValue(context, MemberNames.mention.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.mention.toString(), mention.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return relationshipExtractionMentionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ibmwatsonapi.proxies.RelationshipExtractionMention that = (ibmwatsonapi.proxies.RelationshipExtractionMention) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IbmWatsonApi.RelationshipExtractionMention";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
