// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ibmwatsonapi.proxies;

/**
 * 
 */
public class RelationshipExtractionMentions
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject relationshipExtractionMentionsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "IbmWatsonApi.RelationshipExtractionMentions";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		mentions("IbmWatsonApi.mentions");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RelationshipExtractionMentions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "IbmWatsonApi.RelationshipExtractionMentions"));
	}

	protected RelationshipExtractionMentions(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject relationshipExtractionMentionsMendixObject)
	{
		if (relationshipExtractionMentionsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("IbmWatsonApi.RelationshipExtractionMentions", relationshipExtractionMentionsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a IbmWatsonApi.RelationshipExtractionMentions");

		this.relationshipExtractionMentionsMendixObject = relationshipExtractionMentionsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RelationshipExtractionMentions.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static ibmwatsonapi.proxies.RelationshipExtractionMentions initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ibmwatsonapi.proxies.RelationshipExtractionMentions.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static ibmwatsonapi.proxies.RelationshipExtractionMentions initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ibmwatsonapi.proxies.RelationshipExtractionMentions(context, mendixObject);
	}

	public static ibmwatsonapi.proxies.RelationshipExtractionMentions load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ibmwatsonapi.proxies.RelationshipExtractionMentions.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of mentions
	 */
	public final ibmwatsonapi.proxies.RelationshipExtractionDoc getmentions() throws com.mendix.core.CoreException
	{
		return getmentions(getContext());
	}

	/**
	 * @param context
	 * @return value of mentions
	 */
	public final ibmwatsonapi.proxies.RelationshipExtractionDoc getmentions(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ibmwatsonapi.proxies.RelationshipExtractionDoc result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.mentions.toString());
		if (identifier != null)
			result = ibmwatsonapi.proxies.RelationshipExtractionDoc.load(context, identifier);
		return result;
	}

	/**
	 * Set value of mentions
	 * @param mentions
	 */
	public final void setmentions(ibmwatsonapi.proxies.RelationshipExtractionDoc mentions)
	{
		setmentions(getContext(), mentions);
	}

	/**
	 * Set value of mentions
	 * @param context
	 * @param mentions
	 */
	public final void setmentions(com.mendix.systemwideinterfaces.core.IContext context, ibmwatsonapi.proxies.RelationshipExtractionDoc mentions)
	{
		if (mentions == null)
			getMendixObject().setValue(context, MemberNames.mentions.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.mentions.toString(), mentions.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return relationshipExtractionMentionsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ibmwatsonapi.proxies.RelationshipExtractionMentions that = (ibmwatsonapi.proxies.RelationshipExtractionMentions) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "IbmWatsonApi.RelationshipExtractionMentions";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
