// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ibmwatsonapi.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the IbmWatsonApi module

	public static void openRelationshipExtractionExample(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "IbmWatsonApi.OpenRelationshipExtractionExample", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static java.util.List<ibmwatsonapi.proxies.RelationshipExtractionMention> relationshipExtraction(IContext context, ibmwatsonapi.proxies.RelationshipExtractionMicroflowParams _microflowParams)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("MicroflowParams", _microflowParams == null ? null : _microflowParams.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "IbmWatsonApi.RelationshipExtraction", params);
			java.util.List<ibmwatsonapi.proxies.RelationshipExtractionMention> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<ibmwatsonapi.proxies.RelationshipExtractionMention>();
				for (IMendixObject obj : objs)
					result.add(ibmwatsonapi.proxies.RelationshipExtractionMention.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}